-- EN: Auto-generated by themeswitch.sh — do not edit manually.
--     Sets the Neovim background mode and the active Catppuccin flavor.
--     This file is overwritten by the themeswitch script on each theme change.
-- ES: Generado automáticamente por themeswitch.sh — no editar manualmente.
--     Define el modo de fondo de Neovim y el sabor activo de Catppuccin.
--     Este archivo es sobreescrito por el script themeswitch en cada cambio de tema.
vim.o.background = "dark"
vim.g.catppuccin_flavour = "mocha"
